### ISSUE TITLE
System Eigen needs to be included in CMakeLists.txt of user of open3d_catkin

### ISSUE THREAD

**Issue by nubertj** [leggedrobotics/open3d_slam#14]
E.g. when including PointCloud.h, it complains that "Eigen/core" can not be found.

**Comment by jelavice** [comment]
Is this issue still relevant or has it been resolved with some of the latest changes?

**Comment by nubertj** [comment]
For open3d_slam it was never a problem, just if somebody used open3d_catkin. But I think we can close it, and reopen when somebody again experiences this.
