### ISSUE TITLE
Open3d_catkin can't find PPA-installed Open3D

### ISSUE THREAD

**Issue by YoshuaNava** [leggedrobotics/open3d_slam#39]
Hey! :slightly_smiling_face: 

I followed the [Installation instructions](https://open3d-slam.readthedocs.io/en/latest/installation.html#dependencies), choosing to fetch [Open3D from a PPA](https://open3d-slam.readthedocs.io/en/latest/open3d_catkin.html#install-open3d-from-a-ppa), and then trying to [compile open3d_catkin](https://open3d-slam.readthedocs.io/en/latest/open3d_catkin.html#open3d-catkin-compilation).

However, as soon as I run `catkin build open3d_catkin` (I configure my catkin workspace to build with cmake flag `RelWithDebInfo` by default), I get the following error message:

```
____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________
Errors     << open3d_catkin:cmake /home/ynava/workspaces/open3dslam_ws/logs/open3d_catkin/build.cmake.000.log                                                                                                                                                                                            
INFO: Found Open3D.
Open3D libraries: Open3D::Open3D
Open3D include path: /usr/include , /usr/lib/x86_64-linux-gnu/cmake/Open3D/../../../include/
CMake Error at /opt/ros/noetic/share/catkin/cmake/catkin_package.cmake:300 (message):
  catkin_package() absolute include dir
  '/usr/lib/x86_64-linux-gnu/cmake/Open3D/../../../include/' does not exist
Call Stack (most recent call first):
  /opt/ros/noetic/share/catkin/cmake/catkin_package.cmake:102 (_catkin_package)
  CMakeLists.txt:54 (catkin_package)
```

It seems that the library is not found correctly within my system.

What could be happening?

Thanks in advance for your support.

Best,
Yoshua

**Comment by nubertj** [comment]
Hi yoshua,
We will look at it, thanks for reporting.
Recently Edo and I changed the structure quite a bit to make it more flexible, maybe we missed something.

**Comment by YoshuaNava** [comment]
No prob, thank you for looking into it.

(I wanted to delve a bit deeper but I had to switch tasks, so I opened the issue to not miss on the feedback, as it could happen to other users)

**Comment by jelavice** [comment]
Hi Yoshua,

Thank you for reporting this installation error. I'll try to reproduce it on my machine. Meanwhile, if you wanna play around and test stuff, you could try to build from source. Did you try that yet?

**Comment by nubertj** [comment]
yep, maybe just do it without the ppa installation and check whether this works for you. I am checking the ppa one right now.

**Comment by nubertj** [comment]
@YoshuaNava, I could reproduce your error. 
Can you please check #41?
Hopefully this solves it.

**Comment by nubertj** [comment]
please reopen if there are still issues
