### ISSUE TITLE
Output topic empty

### ISSUE THREAD

**Issue by mich-pest** [leggedrobotics/open3d_slam#55]
Good morning, me and my colleagues from University of Genoa are trying to use the package together with AirSim simulator and its ros_bridge to perform SLAM in a virtual environment. Our vehicle is equipped with a rotative LiDAR (16 channels, 1000 points/sec) which on Rviz produces Pointcloud that seems to be very sparse. Unfortunately, the output topic of your package is available but nothing is received (warning on the status).  
Is it possible that with a very sparse Pointcloud as input, the algorithm fails to build the map? Because we would expect a low quality one in this case.

Thank you

**Comment by nubertj** [comment]
Hi @mich-pest,
Thanks a lot for using our package.
Do you see in the terminal output that the node is receiving and processing the point clouds?
If not, could it be you misspelled the input point cloud topic, or similar?

**Comment by mich-pest** [comment]
Thank you for your reply.
We exclude a problem of mispelling since we copy and paste the topic name related to the visualization of the raw Pointcloud data directly from Rviz.
To provide some more information about our setup, at the moment we have the following settings for the simulated LiDAR:
```
"PublishToRos": 1,
          "SensorType": 6,
          "Enabled": true,
          "NumberOfChannels": 16,
          "VerticalFOVUpper": -5,
          "VerticalFOVLower": -25,
          "PointsPerSecond": 10000,
          "RotationsPerSecond": 10,
          "X": 0,
          "Y": 0,
          "Z": -1.5,
          "DrawDebugPoints": true,
          "DataFrame": "SensorLocalFrame"
```
(taken from settings.json file for AirSim).
Then, we are currently using the params file `params_robosense_rs16.yaml` and the console returns this:

![Screenshot (113)](https://user-images.githubusercontent.com/74416077/208117797-3f17747d-938f-41b8-8646-95cefc5de628.png)

Using that yaml file but setting `is_use_map_initialization` and `is_merge_scans_into_map` parameters to true the error displayed is:
![Screenshot (131)](https://user-images.githubusercontent.com/74416077/208117633-89e2d68e-3e50-4651-96ae-3b560ec4e5f4.png)

Hope it helps, thanks

**Comment by nubertj** [comment]
Thank you for providing additional information. Can you maybe record a rosbag with this topic, upload and share it with us?
Then we can try to reproduce the issue on our side.

**Comment by mich-pest** [comment]
Hi, just an update from our side, the problem should be related to tf we think. Given the error returned in Rviz, reported in the following. 
![Screenshot (133)](https://user-images.githubusercontent.com/74416077/208126748-3e291c12-00df-40b9-a8cf-3d1ace0ce437.png)

We tried to assign `frame_id` (as reported here https://open3d-slam.readthedocs.io/en/latest/localization.html) to the `world_enu` frame but nothing changed.

**Comment by nubertj** [comment]
you can change the frame names here: https://github.com/leggedrobotics/open3d_slam/blob/master/open3d_slam/include/open3d_slam/frames.hpp

The frame_id from above only corresponds to the map initializer.

**Comment by nubertj** [comment]
Otherwise you can also just add an identity transform between map_o3d and world_enu.
