### ISSUE TITLE
Changing pcl of point cloud colorizer to open3d

### ISSUE THREAD

**Issue by nubertj** [leggedrobotics/open3d_slam#63]
The code of the point_cloud_colorizer and point_cloud_colorizer_ros can be found here: https://github.com/leggedrobotics/open3d_slam/tree/feature/colored_dense_maps

@pole95, do you think it would be easily possible to replace the few pcl conversions etc that are happening there to open3d slam?
Fan told me, you helped him/did it for his repo.

**Comment by nubertj** [comment]
we are currently trying to converge to a unified setup for this projection, with an arbitrary number of cameras. This way, we could also use multiple cameras on heap if we would like to. The given version is already running, just needs to be tested and ideally I would like to get rid of pcl in the open3d_<> repo

**Comment by pole95** [comment]
I can take a look. If the pcl type is close to XYZRGB it should not be that much of an issue. We may need to be a bit more explicit during conversions, but this should not affect performance that much.

**Comment by nubertj** [comment]
thanks a lot. It is only these two packages:
https://github.com/leggedrobotics/open3d_slam/tree/feature/colored_dense_maps/ros/point_cloud_colorizer_ros
https://github.com/leggedrobotics/open3d_slam/tree/feature/colored_dense_maps/open3d_utils/point_cloud_colorizer
