### ISSUE TITLE
Question regarding the pointcloud data

### ISSUE THREAD

**Issue by daewoode** [leggedrobotics/open3d_slam#67]
the documentation says the input from open3d slam is only a pointcloud2 message.

i publish the point cloud data via previously read .pcd files. 

are there any other requirements for the pointcloud data or is it sufficient to use the pointcloud2 message with the pointFields x,y,z ?

Does the pointcloud need to be organized?

Best regards

**Comment by nubertj** [comment]
Hi @daewoode,
Yes, that is right. Just publish the point cloud scans as single pc2 messages, and all should work out. 
The point cloud does not need to be organized. 

For the algorithm x,y,z is fully sufficient, and I believe that also the open3d-ros interface can handle x,y,z-only clouds. 
If you run into issues let us know, and we can push a quick fix (normally the scans have x,y,z,I, but I do not think that it should matter for the interface).
